### ISSUE TITLE
Support for SDWebImage 4.X

### ISSUE THREAD

**Issue by geoffmacd** [SDWebImage/SDWebImagePhotosPlugin#4]
### Feature Request Description

This pod should really attempt to use the stable version of SDWebImage if possible. I cannot use this even though it would be useful because I will not update my SDWebImage dependency to a beta version.

**Comment by bpoplauschi** [comment]
@geoffmacd good point. We are getting close to releasing the final 5.0. But we will look into the compatibility of the PhotosPlugin with SDWebImage 4.x

**Comment by dreampiggy** [comment]
This Photos plugin base on the 5.x new feature [Custom Loader](https://github.com/rs/SDWebImage/wiki/Advanced-Usage#custom-loader-50). And it need the `SDWebImageContext` to work for custom options (rather than `SDWebImageOptions` enum value). Current there are no plan, and no simple solution to make it works for 4.x branch.

Actually, some features developed in 5.x, are aim to make this plugin available. If we can do the samething in the 4.x, we maybe not develop those features, actually :)

5.0.0 official release will be available soon (I guess, less than weeks), so at that time you can try to upgrade to the final version instead of beta version.
